import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { chromium } from 'playwright-core'

const origin = process.env.PRACTICE_ORIGIN || 'http://127.0.0.1:5173'
const visualDir = process.env.PRACTICE_VISUAL_DIR || './test-results/practice-e2e'
const chromePath = process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe'
await mkdir(visualDir, { recursive: true })
const browser = await chromium.launch({ executablePath: chromePath, headless: true })
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } })
const errors = [], consoleErrors = [], checks = [], feedbackRequests = []
page.on('pageerror', error => errors.push(error.message))
page.on('request', request => { if (request.method() === 'POST' && request.url().endsWith('/feedback')) feedbackRequests.push(request.postDataJSON()) })
const mark = name => checks.push(name)
let projectId
const api = () => `/api/v1/practice/projects/${projectId}`
async function data(path = '') { const response = await page.request.get(`${origin}${api()}${path}`); assert.equal(response.status(), 200); return response.json() }
async function saved() { await page.getByRole('dialog').waitFor({ state: 'hidden', timeout: 15000 }) }
async function check() {
  const response = page.waitForResponse(response => response.url().endsWith('/reviews') && response.request().method() === 'POST')
  await page.getByRole('button', { name: '检查材料', exact: true }).click()
  const result = await response; assert.equal(result.status(), 201)
  const review = await result.json()
  await page.getByRole('button', { name: '检查材料', exact: true }).waitFor()
  return review
}
async function addEvidence(title, kind, content) {
  await page.getByRole('button', { name: '添加成果证据', exact: true }).click()
  await page.getByLabel('证据名称', { exact: true }).fill(title)
  await page.getByLabel('材料类型').selectOption(kind)
  await page.getByLabel('材料正文').fill(content)
  await page.getByRole('button', { name: '保存证据', exact: true }).click()
  await saved()
}
async function overflow() { return page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth) }

try {
  await page.goto(origin, { waitUntil: 'networkidle' })
  await page.locator('.module-card').filter({ hasText: '实践验证与复盘' }).click()
  await page.locator('.practice-content').waitFor()
  page.on('console', message => {
    if (message.type() !== 'error') return
    // These resource failures are deliberately injected later in this test.
    if (/Failed to load resource.*(?:status of (?:500|503)|net::ERR_FAILED)/.test(message.text())) return
    consoleErrors.push(message.text())
  })
  await page.getByRole('button', { name: '新建实践', exact: true }).click()
  await page.getByLabel('项目名称', { exact: true }).fill('验收：可复现的网络服务部署')
  await page.getByLabel('实践目标', { exact: true }).fill('独立完成一个可复现的网络服务部署，并用材料核对成果')
  await page.getByRole('button', { name: '创建实践', exact: true }).click()
  await saved()
  await page.waitForURL('**/module3/*')
  projectId = new URL(page.url()).pathname.split('/').at(-1)
  const empty = await check()
  assert.ok(empty.findings.every(item => item.verdict === 'insufficient'))
  mark('首页入口、项目创建、空材料保守判定')

  await page.getByRole('button', { name: '生成验收候选', exact: true }).click()
  await page.getByRole('button', { name: '核对 4 项候选' }).click()
  assert.equal(await page.getByRole('dialog').locator('.practice-criterion-form').count(), 4)
  await page.getByRole('button', { name: '确认并保存清单' }).click()
  await saved()
  mark('无密钥模板候选与用户确认')

  await page.getByRole('button', { name: '编辑目标与投入', exact: true }).click()
  await page.getByRole('button', { name: '添加记录', exact: true }).click()
  await page.getByLabel('记录 1 预期下限', { exact: true }).fill('4')
  await page.getByLabel('记录 1 预期上限', { exact: true }).fill('6')
  await page.getByLabel('记录 1 实际投入', { exact: true }).fill('9')
  await page.getByLabel('过程与原因说明').fill('额外 3 小时用于排查环境依赖；这是合成验收案例。')
  await page.getByRole('button', { name: '保存目标与投入' }).click()
  await saved()
  await page.getByText('高于上限 3 小时', { exact: true }).waitFor()
  assert.equal((await data()).comparisons[0].percentDelta, null)
  assert.ok(await page.getByRole('button', { name: '确认本次复盘' }).isDisabled())
  mark('区间投入差异与过期复盘阻止确认')

  await page.getByRole('button', { name: '关联方案', exact: true }).click()
  const source = page.getByLabel('决策场景')
  await source.locator('option').nth(1).waitFor({ state: 'attached' })
  const scenarioId = await source.locator('option').nth(1).getAttribute('value')
  await source.selectOption(scenarioId)
  const versions = page.getByLabel('历史版本', { exact: true })
  await versions.locator('option').nth(1).waitFor({ state: 'attached' })
  const sourceVersionId = await versions.locator('option').nth(1).getAttribute('value')
  await versions.selectOption(sourceVersionId)
  await page.getByLabel('具体方案').selectOption('changed')
  await page.getByRole('button', { name: '保存方案快照' }).click()
  await saved()
  const frozenOrigin = (await data()).decisionOrigin
  assert.equal(frozenOrigin.optionKey, 'changed')
  mark('选定决策版本与具体方案，冻结来源快照')

  await addEvidence('HTTP 与请求日志', 'log', 'HTTP/1.1 200 OK\nrequest_id=acceptance-001 method=GET path=/health status=200\n本材料是合成演示案例。')
  const partial = await check()
  assert.deepEqual(partial.findings.map(item => item.verdict), ['supported', 'insufficient', 'supported', 'insufficient'])
  await page.locator('.practice-citation').first().click()
  await page.locator('.practice-code-highlight').waitFor()
  assert.match(await page.locator('.practice-code-highlight').textContent(), /HTTP\/1.1 200 OK/)
  await page.getByRole('button', { name: '查看验收项：HTTPS 配置与访问' }).click()
  await page.getByText('补充：TLS 监听、证书配置与 HTTPS 成功访问日志。', { exact: true }).waitFor()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: join(visualDir, 'practice-partial-1280x720.png') })
  mark('部分材料、补验建议与引用原文行高亮')

  const evidencePath = `**${api()}/evidence`
  await page.getByRole('button', { name: '添加成果证据', exact: true }).click()
  await page.getByLabel('证据名称', { exact: true }).fill('TLS 配置')
  await page.getByLabel('材料类型').selectOption('config')
  await page.getByLabel('材料正文').fill('listen 443 ssl;\nssl_certificate /demo/fullchain.pem;\nssl_certificate_key /demo/private.key;')
  await page.route(evidencePath, route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { code: 'TEST_OUTAGE', message: '模拟保存失败，请重试。' } }) }))
  await page.getByRole('button', { name: '保存证据', exact: true }).click()
  await page.getByRole('alert').getByText('模拟保存失败，请重试。').waitFor()
  assert.equal(await page.getByLabel('证据名称', { exact: true }).inputValue(), 'TLS 配置')
  await page.keyboard.press('Escape'); await saved()
  await page.unroute(evidencePath)
  await page.getByRole('button', { name: '添加成果证据', exact: true }).click()
  await page.getByText('已恢复未提交的材料草稿；仍需保存到后端。').waitFor()
  assert.equal(await page.getByLabel('证据名称', { exact: true }).inputValue(), 'TLS 配置')
  await page.getByRole('button', { name: '保存证据', exact: true }).click(); await saved()
  mark('证据保存失败、Escape 关闭、草稿恢复与成功重试')
  await addEvidence('HTTPS 访问', 'log', 'HTTPS GET https://demo.local/health -> 200')
  await addEvidence('完整部署说明', 'note', '环境：Ubuntu 24.04，Node.js 20\n启动：npm run start\n验证：curl https://demo.local/health')

  let completedOnServer
  const reviewPath = `**${api()}/reviews`
  await page.route(reviewPath, async route => {
    if (route.request().method() !== 'POST') return route.continue()
    const response = await route.fetch()
    assert.equal(response.status(), 201)
    completedOnServer = await response.json()
    await route.abort('failed')
  })
  await page.getByRole('button', { name: '检查材料', exact: true }).click()
  await page.getByRole('button', { name: '重试上次检查' }).waitFor()
  await page.unroute(reviewPath)
  await page.getByRole('button', { name: '重试上次检查' }).click()
  await page.getByRole('heading', { name: '复盘版本 3：材料支持哪些结果' }).waitFor()
  const complete = await data(`/reviews/${completedOnServer.id}`)
  assert.ok(complete.findings.every(item => item.verdict === 'supported'))
  assert.equal((await data('/reviews')).length, 3)
  assert.deepEqual((await data()).decisionOrigin, frozenOrigin)
  mark('补交完整材料、响应丢失后原请求重试且复盘无重复')

  await page.getByLabel('对照版本').selectOption(partial.id)
  await page.getByRole('button', { name: '查看验收项：HTTPS 配置与访问' }).click()
  await page.getByText('与版本 2 比较：证据不足 → 材料支持').waitFor()
  await page.getByRole('button', { name: '查看验收项：基础服务访问' }).click()
  await page.getByRole('button', { name: '纠正判定', exact: true }).click()
  await page.getByLabel('人工判定').selectOption('insufficient')
  await page.getByLabel('修正理由').fill('这项结果还需要由用户核对当前环境。')
  await page.getByRole('button', { name: '暂存人工修正' }).click(); await saved()
  await page.getByText('补充：HTTP 状态行或包含请求路径与状态码的访问日志。', { exact: true }).waitFor()
  await page.getByRole('button', { name: '纠正判定', exact: true }).click()
  await page.getByLabel('人工判定').selectOption('supported')
  await page.getByLabel('修正理由').fill('用户已核对第 1 行状态码与本次服务访问结果。')
  await page.getByRole('button', { name: '暂存人工修正' }).click(); await saved()
  await page.getByRole('button', { name: '确认本次复盘' }).click()
  await page.getByLabel('能力反馈说明').waitFor()
  const skillName = '网络服务部署'.repeat(20)
  await page.getByLabel('拟关联技能名称（仅供后续核对）').fill(skillName)
  const confirmed = await data(`/reviews/${complete.id}`)
  assert.equal(confirmed.confirmation.overrides.length, 1)
  assert.equal(confirmed.findings[0].verdict, 'supported')
  assert.equal(confirmed.confirmation.overrides[0].citations[0].quote, 'HTTP/1.1 200 OK')
  mark('补验版本比较、有效人工引用、原始结果与确认并存')

  const feedbackPath = `**${api()}/feedback`
  const editedNote = `${await page.getByLabel('能力反馈说明').inputValue()}\n本次反馈由用户核对后保存。`
  await page.getByLabel('能力反馈说明').fill(editedNote)
  await page.route(feedbackPath, route => route.request().method() === 'POST' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { code: 'TEST_OUTAGE', message: '模拟反馈保存失败，请重试。' } }) }) : route.continue())
  await page.getByRole('button', { name: '保存反馈参考' }).click()
  await page.getByRole('alert').getByText('模拟反馈保存失败，请重试。').waitFor()
  await page.unroute(feedbackPath)
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByLabel('能力反馈说明').waitFor()
  assert.equal(await page.getByLabel('拟关联技能名称（仅供后续核对）').inputValue(), skillName)
  assert.equal(await page.getByLabel('能力反馈说明').inputValue(), editedNote)
  await page.getByRole('button', { name: '保存反馈参考' }).click()
  await page.locator('.practice-saved-feedback article').nth(1).waitFor()
  assert.equal(feedbackRequests.at(-1).requestId, feedbackRequests.at(-2).requestId)
  const feedback = await data('/feedback')
  assert.equal(feedback.length, 2)
  assert.ok(feedback.every(item => item.delivery === 'reference_only' && item.externalRecordId === null))
  assert.equal(feedback.find(item => item.target === 'ability').targetName, skillName)
  assert.ok(feedback.find(item => item.target === 'decision').note.includes(sourceVersionId))
  assert.match(feedback.find(item => item.target === 'decision').note, /方案 changed/)
  assert.match(feedback.find(item => item.target === 'decision').note, /原假设：/)
  assert.match(feedback.find(item => item.target === 'decision').note, /仅作来源参考/)
  await page.getByRole('button', { name: '复制摘要' }).first().click()
  mark('反馈失败与刷新后草稿恢复、请求标识复用、保存参考与复制摘要')

  await page.reload({ waitUntil: 'networkidle' })
  await page.locator('.practice-saved-feedback article').nth(1).waitFor()
  await page.locator('.practice-history-item').filter({ hasText: '复盘版本 2' }).click()
  await page.getByRole('button', { name: '查看验收项：基础服务访问' }).click()
  await page.locator('.practice-citation').first().click()
  assert.match(await page.locator('.practice-evidence-viewer').textContent(), /复盘时的材料快照/)
  assert.ok(await page.getByRole('button', { name: '确认本次复盘' }).isDisabled())
  await page.getByText('查看复盘 2 的投入快照').click()
  await page.locator('.practice-history-item').filter({ hasText: '复盘版本 3' }).click()
  mark('刷新恢复、历史材料与投入快照、过期确认限制')

  await page.evaluate(() => window.scrollTo(0, 0))
  const desktopOverflow = await overflow(); assert.ok(desktopOverflow <= 0)
  await page.screenshot({ path: join(visualDir, 'practice-complete-1280x720.png') })
  await page.setViewportSize({ width: 360, height: 800 })
  await page.reload({ waitUntil: 'networkidle' })
  await page.locator('.practice-saved-feedback article').nth(1).waitFor()
  const mobileOverflow = await overflow(); assert.ok(mobileOverflow <= 0)
  await page.screenshot({ path: join(visualDir, 'practice-360x800.png') })
  await page.screenshot({ path: join(visualDir, 'practice-mobile-full.png'), fullPage: true })
  await page.getByRole('button', { name: '编辑目标与投入', exact: true }).focus()
  await page.keyboard.press('Enter'); await page.getByRole('dialog').waitFor()
  assert.ok((await page.getByRole('dialog').boundingBox()).width <= 360)
  assert.ok(await overflow() <= 0)
  await page.screenshot({ path: join(visualDir, 'practice-mobile-editor.png') })
  await page.getByRole('dialog').getByRole('button', { name: '关闭弹窗' }).focus()
  await page.keyboard.press('Shift+Tab')
  assert.equal(await page.evaluate(() => document.activeElement?.closest('[role=dialog]') !== null), true)
  await page.keyboard.press('Escape'); await saved()
  assert.equal(await page.getByRole('button', { name: '编辑目标与投入', exact: true }).evaluate(item => item === document.activeElement), true)
  mark('桌面与手机无溢出、键盘打开/关闭、焦点恢复')

  const emptyPage = await browser.newPage({ viewport: { width: 360, height: 800 } })
  emptyPage.on('pageerror', error => errors.push(error.message))
  await emptyPage.route('**/api/v1/practice/projects', route => route.fulfill({ status: 200, contentType: 'application/json', body: '[]' }))
  await emptyPage.goto(`${origin}/module3`, { waitUntil: 'networkidle' })
  await emptyPage.getByRole('heading', { name: '开始一项真实实践' }).waitFor()
  await emptyPage.screenshot({ path: join(visualDir, 'practice-mobile-empty.png') })
  await emptyPage.close()
  const longPage = await browser.newPage({ viewport: { width: 360, height: 800 } })
  longPage.on('pageerror', error => errors.push(error.message))
  const longProject = structuredClone(await data())
  longProject.title = '最长标题'.repeat(30)
  longProject.goal = '核对实践的真实成果与材料。'.repeat(70)
  longProject.evidence[0].title = '成果原文'.repeat(30)
  longProject.evidence[0].content += '\n<script>throw new Error("材料应只作文本显示")</script>\n' + '长日志'.repeat(3000)
  const longReview = structuredClone(await data(`/reviews/${complete.id}`))
  longReview.input = structuredClone(longProject)
  longReview.input.criteria[0].title = '可观察标准'.repeat(24)
  longReview.input.criteria[0].standard = '按原始材料核对验收标准。'.repeat(80)
  longReview.findings[0].reason = '这里展示需要核对的材料依据与观察限制。'.repeat(90)
  longReview.confirmation.overrides[0].reason = longReview.findings[0].reason
  await longPage.route(`**${api()}`, route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(longProject) }))
  await longPage.route(`**${api()}/reviews/${complete.id}`, route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify(longReview) }))
  await longPage.goto(`${origin}/module3/${projectId}`, { waitUntil: 'networkidle' })
  await longPage.locator('.practice-overview').waitFor()
  await longPage.setViewportSize({ width: 1280, height: 720 })
  assert.ok(await longPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  await longPage.setViewportSize({ width: 360, height: 800 })
  assert.ok(await longPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  assert.match(await longPage.locator('.practice-code-view').textContent(), /<script>/)
  await longPage.screenshot({ path: join(visualDir, 'practice-mobile-long-text.png') })
  await longPage.close()
  assert.deepEqual(errors, [])
  assert.deepEqual(consoleErrors, [])
  mark('空项目状态与无新增页面运行错误')
  mark('最长中文标题、目标、判定与长日志无页面溢出；HTML 材料按文本呈现')
  const report = { projectId, reviewIds: [empty.id, partial.id, complete.id], feedbackIds: feedback.map(item => item.id), frozenOrigin,
    desktopOverflow, mobileOverflow, pageErrors: errors, unexpectedConsoleErrors: consoleErrors, checks, verifiedAt: new Date().toISOString() }
  await writeFile(join(visualDir, 'acceptance.json'), JSON.stringify(report, null, 2))
  console.log(JSON.stringify(report, null, 2))
} catch (error) {
  await page.screenshot({ path: join(visualDir, 'failure.png'), fullPage: true }).catch(() => {})
  console.error('页面提示：', await page.locator('[role=alert]').allTextContents())
  console.error('未完成的表单：', await page.locator('[role=dialog] :invalid').evaluateAll(items => items.map(item => ({ tag: item.tagName, message: item.validationMessage }))))
  console.error('运行错误：', errors)
  throw error
} finally { await browser.close() }
